name: python

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[tests] --index-url https://gitlab.mpcdf.mpg.de/api/v4/projects/2187/packages/pypi/simple
        pip install types-PyYAML
    - name: pycodestyle
      run: |
        python -m pycodestyle --ignore=E501,E701,E731 eelsdbparser tests
    - name: pylint
      run: |
        python -m pylint eelsdbparser tests
    - name: mypy
      run: |
        python -m mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional eelsdbparser tests
    - name: Test with pytest
      if: success() || failure()
      run: |
        python -m pytest -sv tests
